### PR TITLE
DBC refactoring

### PR DESCRIPTION
**Pull request by samparent97**
* Renames the dbcs to match our naming style. Also removes the redundant can portion of the name.
  * This makes it possible to get good package naming in hil
* Removes the legacy folder

### CODE REVIEW

**Review by tullom — COMMENTED** [review]
Have the legacy deleted DBC files had their functionality migrated to another place (like HIL)? or are they no longer needed?

**Comment by samparent97** [comment]
> Have the legacy deleted DBC files had their functionality migrated to another place (like HIL)? or are they no longer needed?

No longer needed. The messages are either unused or they have been moved to one of the dbcs we maintain

**Review by tullom — APPROVED** [review]
LGTM

**Review by tullom — APPROVED** [review]
LGTM

**Pull request merged**
